[package]
name = "xmlhub-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
ahtml = { version = "0.3" }
xmltree = "0.11.0"
xml-rs = "0.8.20"
anyhow = "1.0.65"
clap = { version = "3", features = ["derive"] }
chrono = "0.4"
lazy_static = "1.4"
itertools = "0.11.0"
thiserror = "=1.0.37"
# use older version to avoid additional, unknown, dependencies
# (separate newer versions of the windows dependencies)
os_info = "=3.7"
rayon = "=1.5.3"
