#!/bin/bash
set -meuo pipefail
IFS=

cd ~/xmlhub-indexer

# XXX todo: fetch, signature check.

cargo build --quiet --release

# (Note: xmlhub now sets resource limits internally in every forked
# worker child; you don't need to set any limits outside.)

exec target/release/xmlhub build "${XMLHUB_CHECKOUT-$HOME/tmp/xmlhub}" \
     --localtime --max-log-file-size 100000 --max-log-files 20 --quiet \
     --daemon "$@"

